language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
script:
  - pip install  -qq -r requirements.txt -t build/code/
  - sam package --template-file template.yaml --output-template-file build/packaged.yaml --s3-bucket yorpg-develop
  - aws cloudformation deploy --template-file build/packaged.yaml --stack-name yorpg-develop --capabilities CAPABILITY_IAM