version: 0.2

phases:
  install:
    commands:
    - pip install -qq -r dev-requirements.txt
  build:
    commands:
    - pip install  -qq -r requirements.txt -t code/
  post_build:
    commands:
    - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket yorpg-develop
    - aws cloudformation deploy --template-file packaged.yaml --stack-name yorpg-develop --capabilities CAPABILITY_IAM
    finally:
    - ls -al
    - ls -al build/
artifacts:
  files:
  - 'code'
